primary:
  initContainers:
    - name: volume-permissions
      image: busybox
      command: ['sh', '-c', 'chown -R 1001:1001 /bitnami/postgresql']
      volumeMounts:
      - name: data
        mountPath: /bitnami/postgresql
  persistence:
    existingClaim: postgresql-pvc
