version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Starting build at `date`
      # Build the database Docker image
      - echo Building the database Docker image...
      - cd $CODEBUILD_SRC_DIR/db
      - docker build -t $DB_IMAGE_NAME:$CODEBUILD_BUILD_NUMBER .
      - docker tag $DB_IMAGE_NAME:$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$DB_IMAGE_NAME:$CODEBUILD_BUILD_NUMBER

      # Build application Docker image
      - echo Building the application Docker image...
      - cd $CODEBUILD_SRC_DIR/analytics
      - docker build -t $APP_IMAGE_NAME:$CODEBUILD_BUILD_NUMBER .
      - docker tag $APP_IMAGE_NAME:$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_IMAGE_NAME:$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - echo Completed build at `date`
      # Pushing the database Docker image
      - echo Pushing the database Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$DB_IMAGE_NAME:$CODEBUILD_BUILD_NUMBER

      # Pushing the application Docker image
      - echo Pushing the application Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_IMAGE_NAME:$CODEBUILD_BUILD_NUMBER
