apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  DB_NAME: postgres
  DB_USER: postgres
  DB_HOST: 'postgresql-service.default.svc.cluster.local'
  DB_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASS: eGg2MkM2Z0REUQ==
