apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  DB_NAME: postgres
  DB_USERNAME: postgres
  DB_HOST: 'coworking-postgresql-db.default.svc.cluster.local'
  DB_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: eGg2MkM2Z0REUQ==
